spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: 'TRUE'
    hibernate:
      ddl-auto: update
    open-in-view: 'false'
  mvc:
    hiddenmethod:
      filter:
        enabled: 'true'
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: 'NewPassword'
    username: 'root'
    url: jdbc:mysql://localhost:3306/greencom_db?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "${GOOGLE_OAUTH_CLIENT_ID}"
            client-secret: "${GOOGLE_OAUTH_CLIENT_SECRET}"
          facebook:
            client-id: "${FACEBOOK_OAUTH_CLIENT_ID}"
            client-secret: "${FACEBOOK_OAUTH_CLIENT_SECRET}"
            scope:
              - email
              - public_profile
logging:
  level:
    org:
      hibernate:
        type:
          descriptor: TRACE
        SQL: DEBUG
      nodeValue: WARN
      springframework:
        security: DEBUG
    blog: WARN
loyalty:
  service:
    url: http://localhost:8081
server:
  port: 8080
greencom:
    admin:
      username: "${GREENCOM_ADMIN_USERNAME}"
      password: "${GREENCOM_ADMIN_PASSWORD}"
